language: node_js
sudo: false

node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'

env:
  matrix:
    - TEST_SUITE=senecajs/seneca
    - TEST_SUITE=senecajs/seneca-entity
    - TEST_SUITE=senecajs/seneca-user
    - TEST_SUITE=senecajs/seneca-transport

before_script:
  - export SENECA_CURRENT=v3.3.0
  - TEST_SUITE_FOLDER=$(basename $TEST_SUITE)
  - echo "TEST_SUITE:$TEST_SUITE"
  - echo "TEST_SUITE_FOLDER:$TEST_SUITE_FOLDER"
  - echo "SENECA_INSTALL:$SENECA_INSTALL";
  - if [ $TEST_SUITE_FOLDER == 'seneca' ]; then
      git clone https://github.com/$TEST_SUITE --branch $SENECA_CURRENT --single-branch
      cd $TEST_SUITE_FOLDER;
      npm install;
    fi
  - if [ $TEST_SUITE_FOLDER != 'seneca' ]; then
      git clone https://github.com/$TEST_SUITE;
      cd $TEST_SUITE_FOLDER;
      npm install;
    fi

cache:
  directories:
      - node_modules

after_script:
  - npm run coveralls

